import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
// Includes software WebGL startup, full-page exports and repeated viewport reconstruction.
test.describe.configure({ timeout: 60000 });
async function openElectron(page: import('@playwright/test').Page, inspect = true) {
  await page.goto('/');
  if (page.viewportSize()!.width < 850) await page.getByRole('button', { name: 'Open experiment library' }).click();
  await page.getByRole('button', { name: /Polarization, spin & motion/ }).click();
  await expect(page.getByRole('button', { name: 'Run electron', exact: true })).toBeEnabled();
  if (inspect) await page.getByLabel('Zepton selector', { exact: true }).check();
}
test('stationary electron begins absent in a cube with selection opt-in and resolving 3D lines', async ({ page }) => {
  await openElectron(page, false);
  await expect(page.getByLabel('Zepton selector', { exact: true })).not.toBeChecked();
  await expect(page.getByLabel('Central slab cutaway', { exact: true })).not.toBeChecked();
  await expect(page.getByText('Unpolarized ZPF · electron not yet introduced', { exact: true })).toBeVisible();
  await expect(page.getByTestId('electron-pair-centre')).toHaveCount(0);
  await page.locator('.light-viewport-shell').screenshot({ path: 'test-results/electron-cube-initial.png' });
  await page.getByRole('slider', { name: 'Electron timeline' }).fill('80');
  await expect(page.getByTestId('electron-tick')).toContainText('Tick 80');
  await page.locator('.light-viewport-shell').screenshot({ path: 'test-results/electron-cube-forming.png' });
  await page.getByRole('button', { name: 'Show fully aligned field' }).click();
  await page.locator('.light-viewport-shell').screenshot({ path: 'test-results/electron-cube-aligned.png' });
  await page.getByLabel('Zepton selector', { exact: true }).check();
  await expect(page.getByTestId('electron-pair-centre')).toBeVisible();
  await page.getByLabel('Zepton selector', { exact: true }).uncheck();
  await expect(page.getByTestId('electron-pair-centre')).toHaveCount(0);
  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await expect(page.getByText('Unpolarized ZPF · electron not yet introduced', { exact: true })).toBeVisible();
});
test('spin shells reveal counter-motion, radial falloff, full 3D and migrated files', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await openElectron(page); await page.getByRole('button', { name: /Spin in the surrounding field/ }).click();
  await page.getByRole('button', { name: 'Advance 1 τ' }).click();
  await page.getByRole('button', { name: 'Inspect spin band at 0.6 R', exact: true }).click();
  await expect(page.getByTestId('electron-spin-rate')).toHaveText('19.10° / τ');
  const centre = await page.getByTestId('electron-pair-centre').innerText();
  await page.getByRole('button', { name: 'Advance 1 τ' }).click();
  await expect(page.getByTestId('electron-pair-centre')).toHaveText(centre);
  await page.locator('.light-viewport-shell').screenshot({ path: 'test-results/spin-shells-cutaway.png' });
  await page.getByRole('button', { name: 'Inspect spin band at 2.8 R', exact: true }).click();
  await expect(page.getByTestId('electron-spin-rate')).toHaveText('0.88° / τ');
  await page.getByLabel('Full 3D shells', { exact: true }).check();
  await expect(page.getByLabel('Central slab cutaway', { exact: true })).not.toBeChecked();
  await page.locator('.light-viewport-shell').screenshot({ path: 'test-results/spin-shells-3d.png' });
  await page.getByLabel('Electron spin projection').selectOption('-1');
  await page.getByRole('button', { name: 'Apply electron parameters' }).click();
  await expect(page.getByTestId('electron-spin-rate')).toHaveText('-0.88° / τ');
  await expect(page.locator('.electron-positive')).toContainText('↺');
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Save electron', exact: true }).click();
  const saved = JSON.parse(await readFile((await (await download).path())!, 'utf8'));
  expect(saved.version).toBe(3); expect(saved.state.model).toBe('electron-polarization/3');
  saved.version = 1; saved.state.model = 'electron-polarization/1'; delete saved.view.shells;
  await page.getByLabel('Import electron experiment').setInputFiles({ name: 'legacy.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(saved)) });
  await expect(page.getByRole('status', { name: 'Electron experiment status' })).toContainText('Updated an older experiment');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Shell close-up', exact: true }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('.light-viewport-shell').screenshot({ path: 'test-results/spin-shells-mobile.png' });
  await page.getByLabel('Charge motion arrows', { exact: true }).uncheck();
  await expect(page.getByLabel('Local rotation sense', { exact: true })).not.toBeChecked();
  expect(errors).toEqual([]);
});
test('electron stages, Faraday layers, replay and files preserve fixed centres', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message)); await openElectron(page);
  await expect(page.getByLabel('Faraday lines from polarization', { exact: true })).toBeChecked();
  await page.getByRole('button', { name: 'Show fully aligned field' }).click();
  await expect(page.getByTestId('electron-tick')).toContainText('Tick 360');
  await page.screenshot({ path: 'test-results/electron-electric.png', fullPage: true });
  const centre = await page.getByTestId('electron-pair-centre').innerText();
  await page.getByRole('button', { name: /Spin in the surrounding field/ }).click();
  await page.getByRole('button', { name: 'Advance 1 τ' }).click();
  await expect(page.getByTestId('electron-position')).toHaveText('0.000R');
  await expect(page.getByTestId('electron-pair-centre')).toHaveText(centre);
  await page.screenshot({ path: 'test-results/electron-spin.png', fullPage: true });
  await page.getByRole('button', { name: /03.*Moving electron/ }).click();
  await page.getByRole('button', { name: 'Electron at path centre' }).click();
  await expect(page.getByTestId('electron-B-motion')).toContainText('-0.0468');
  await page.getByRole('slider', { name: 'Electron velocity', exact: true }).fill('-0.15');
  await page.getByRole('button', { name: 'Apply electron parameters' }).click();
  await page.getByRole('button', { name: 'Electron at path centre' }).click();
  await expect(page.getByTestId('electron-B-motion')).toHaveText('0, 0, 0.0468');
  await page.getByLabel('Faraday lines from polarization', { exact: true }).uncheck();
  await page.getByRole('button', { name: 'Capture electron checkpoint' }).click();
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Save electron', exact: true }).click(); const file = await (await download).path();
  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await page.getByRole('button', { name: 'Restore electron tick 2880' }).click();
  await page.getByLabel('Import electron experiment').setInputFiles(file!);
  await expect(page.getByRole('status', { name: 'Electron experiment status' })).toContainText('Loaded electron tick 2880');
  await expect(page.getByLabel('Faraday lines from polarization', { exact: true })).not.toBeChecked();
  await page.getByLabel('Import electron experiment').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{}') });
  await expect(page.getByRole('status', { name: 'Electron experiment status' })).toContainText('Could not load');
  await expect(page.getByTestId('electron-tick')).toContainText('Tick 2880');
  await page.getByRole('button', { name: 'Medium laboratory', exact: true }).click();
  await page.getByRole('button', { name: /Polarization, spin & motion/ }).click();
  await expect(page.getByTestId('electron-tick')).toContainText('Tick 2880');
  await page.getByLabel('Faraday lines from polarization', { exact: true }).check();
  await page.screenshot({ path: 'test-results/electron-moving.png', fullPage: true });
  expect(errors).toEqual([]);
});
test('electron mobile layers, masked probe and exports work', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await openElectron(page);
  await page.getByRole('button', { name: 'Show fully aligned field' }).click();
  await expect(page.getByLabel('Central slab cutaway', { exact: true })).not.toBeChecked();
  await page.getByLabel('Reduced flashing & camera motion').check();
  await expect(page.getByTestId('electron-tick')).toContainText('Tick 360');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const image = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export electron image' }).click(); expect((await image).suggestedFilename()).toBe('zeropoint-electron.png');
  const csv = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export electron CSV' }).click(); expect((await csv).suggestedFilename()).toContain('reference-sequence.csv');
  await page.getByRole('slider', { name: 'Probe Y', exact: true }).fill('0');
  await page.getByRole('button', { name: 'Apply electron parameters' }).click();
  await expect(page.getByText('Probe lies inside the 0.3 R numerical mask. Field values are excluded.')).toBeVisible();
  expect((await page.request.get('/docs/Polarization-Notes.md')).ok()).toBe(true);
  await page.screenshot({ path: 'test-results/electron-mobile.png', fullPage: true });
});
test('electron pauses when hidden and recovers actual WebGL loss', async ({ page }) => {
  await openElectron(page); await page.getByRole('button', { name: 'Run electron', exact: true }).click();
  await expect.poll(async () => parseInt((await page.getByTestId('electron-tick').innerText()).split(' ')[1])).toBeGreaterThan(0);
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: true }); document.dispatchEvent(new Event('visibilitychange')); });
  await expect(page.getByRole('button', { name: 'Run electron', exact: true })).toBeVisible();
  await page.evaluate(() => { delete (document as unknown as Record<string, unknown>).hidden; });
  await page.getByRole('button', { name: 'Show fully aligned field' }).click();
  await expect(page.getByTestId('electron-tick')).toContainText('Tick 360');
  await page.locator('.electron-viewport canvas').evaluate((canvas: HTMLCanvasElement) => canvas.getContext('webgl2')!.getExtension('WEBGL_lose_context')!.loseContext());
  await expect(page.getByRole('heading', { name: 'Electron viewport needs attention' })).toBeVisible();
  await page.getByRole('button', { name: 'Recover electron viewport' }).click();
  await expect(page.getByRole('heading', { name: 'Electron viewport needs attention' })).not.toBeVisible();
  await expect(page.getByTestId('electron-tick')).toContainText('Tick 360');
  await page.getByRole('slider', { name: 'Electron timeline' }).press('End');
  await expect(page.getByRole('button', { name: 'Run electron', exact: true })).toBeDisabled();
});
