import { BrandMark } from '../app/BrandMark';
import { RepositoryLink } from '../app/RepositoryLink';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowLeft, Box, Download, Focus, Info, Pause, Play, RotateCcw, Save, SkipForward } from 'lucide-react';
import { downloadFile } from '../persistence/experiment';
import { ALPHA, C, DEFAULT_ELECTRON, DEFAULT_ELECTRON_VIEW, ELECTRON_DT, ELECTRON_END, ELECTRON_MODEL, LATTICE_SAMPLES, SHELL_RADII, SAMPLES_PER_SHELL, G_FACTOR, RADIUS, TAU, alignmentProgress, electronPresence, electronX, enclosedCharge, parseElectronFile, probePosition, referenceFields, spinRateAtRadius, velocity } from './model';
import type { ElectronMode, ElectronParameters, ElectronState, ElectronView, ElectronLayer } from './model';
import type { ElectronRenderer } from './ElectronRenderer';
import { SpinSection } from './SpinSection';
import { ChargeMotion } from './ChargeMotion';
import { ElectronProperties } from './ElectronProperties';
import { displayedDipole, shellCentre, shellSense, SHELL_COLOURS } from './spinGeometry';
import { useElectron } from './useElectron';
import '../light/light.css';
import './electron.css';

const modes: { id: ElectronMode; title: string; subtitle: string; description: string }[] = [
  { id: 'electric', title: 'Stationary electron', subtitle: '01 / ELECTRIC POLARIZATION', description: 'Start with an unpolarized cubic medium. The electron appears, and nearby pairs align first as a three-dimensional electric pattern resolves.' },
  { id: 'spin', title: 'Spin in the surrounding field', subtitle: '02 / LOCAL, COORDINATED ROTATION', description: 'Following Fig. 2: neighboring zeptons turn locally as they polarize around the stationary electron. Compare the spherical field and equatorial section, then inspect how opposite charge motions contribute to current. Alternating whole bands is an optional extension.' },
  { id: 'moving', title: 'Moving electron', subtitle: '03 / MAGNETIC RESPONSE', description: 'As the electron passes, nearby pairs turn locally. Reverse its velocity to reverse the motion-induced magnetic field.' },
];
const vector = (v: number[]) => v.map(n => Math.abs(n) < 1e-9 ? '0' : n.toFixed(4)).join(', ');

/** Render and coordinate the electron polarization laboratory. */
export function ElectronExperiment({ active, onBack }: { active: boolean; onBack: () => void }) {
  const { state, latest, sink, send, error, restart } = useElectron(active);
  const [draft, setDraft] = useState({ ...DEFAULT_ELECTRON }), [view, setView] = useState<ElectronView>(() => ({ ...DEFAULT_ELECTRON_VIEW, reducedMotion: matchMedia('(prefers-reduced-motion: reduce)').matches }));
  const [selected, setSelected] = useState<number | null>(null), [camera, setCamera] = useState<'front' | 'orbit' | 'probe' | 'shell'>('orbit');
  const [graphicsError, setGraphicsError] = useState(''), [revision, setRevision] = useState(0), [notice, setNotice] = useState('');
  const [checkpoints, setCheckpoints] = useState<ElectronState[]>([]);
  const host = useRef<HTMLDivElement>(null), renderer = useRef<ElectronRenderer | null>(null), input = useRef<HTMLInputElement>(null);
  const viewRef = useRef(view), selectedRef = useRef(selected), cameraRef = useRef(camera); viewRef.current = view; selectedRef.current = selected; cameraRef.current = camera;
  const onPick = useCallback((id: number) => { if (viewRef.current.inspect) setSelected(id); }, []);
  useEffect(() => {
    if (!active || !host.current) return; let disposed = false, r: ElectronRenderer | undefined;
    import('./ElectronRenderer').then(({ ElectronRenderer }) => {
      if (disposed || !host.current) return;
      r = new ElectronRenderer(host.current, viewRef.current, onPick, message => { setGraphicsError(message); send({ type: 'run', value: false }); }); renderer.current = r; sink.current = s => r?.update(s);
      if (latest.current) r.update(latest.current); r.select(selectedRef.current); r.cameraPreset(cameraRef.current);
    }).catch(e => { if (!disposed) { setGraphicsError(String(e)); send({ type: 'run', value: false }); } });
    return () => { disposed = true; sink.current = null; renderer.current = null; r?.dispose(); };
  }, [active, revision, latest, sink, send, onPick]);
  useEffect(() => { renderer.current?.setView(view); }, [view]);
  useEffect(() => { renderer.current?.select(selected); }, [selected]);
  useEffect(() => { renderer.current?.cameraPreset(camera); }, [camera, view.cutaway, state?.parameters.axis]);
  useEffect(() => {
    if (!active) return;
    const key = (e: KeyboardEvent) => {
      const target = e.target as HTMLElement; if (['INPUT', 'SELECT', 'BUTTON', 'A', 'TEXTAREA'].includes(target.tagName) || target.isContentEditable || error) return;
      if (e.code === 'Space' && !graphicsError) { e.preventDefault(); send({ type: 'run', value: !latest.current?.running }); }
      if (e.code === 'ArrowRight') { e.preventDefault(); send({ type: 'step' }); }
    };
    window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key);
  }, [active, send, latest, error, graphicsError]);
  const s = state ?? { model: ELECTRON_MODEL, tick: 0, parameters: DEFAULT_ELECTRON, running: false, speed: 1 };
  const p = s.parameters, mode = modes.find(m => m.id === p.mode)!, time = s.tick * ELECTRON_DT, ready = !!state && !error, finished = s.tick === ELECTRON_END;
  const field = referenceFields(s, probePosition(p)), picked = !view.inspect || selected === null ? null : displayedDipole(s, selected, view.spinDisplay), flux = enclosedCharge(s, 2);
  /** Switch to a fresh paused run for the selected electron mode. */
  function changeMode(id: ElectronMode) {
    const next = { ...p, mode: id }; setDraft(next); send({ type: 'configure', parameters: next });
    setView(v => ({ ...v, intrinsic: false, faraday: id !== 'spin', radius: false, cutaway: false, shells: id === 'spin' ? true : v.shells })); setCamera(id === 'spin' ? 'shell' : 'orbit'); setNotice('View changed. The sequence is paused at its start.');
  }
  /** Download the current electron experiment state. */
  function save() {
    if (!latest.current) return; const { model, tick, parameters } = latest.current;
    downloadFile(`zeropoint-electron-${p.mode}-tick-${tick}.json`, JSON.stringify({ format: 'zeropoint-electron', version: 3, state: { model, tick, parameters }, view }), 'application/json'); setNotice(`Saved electron state at tick ${tick}.`);
  }
  /** Load and restore an electron experiment file selected by the user. */
  async function load(file?: File) {
    if (!file) return;
    try { if (file.size > 100000) throw new Error('File exceeds 100 KB.'); const saved = parseElectronFile(await file.text()); send({ type: 'restore', state: saved.state }); setDraft(saved.state.parameters); setView(saved.view); setNotice(`Loaded electron tick ${saved.state.tick}. Playback is paused.${saved.migrated ? ' Updated an older experiment to the cubic medium and revised polarization sequence.' : ''}`); }
    catch (e) { setNotice(`Could not load: ${e instanceof Error ? e.message : String(e)}`); }
    finally { if (input.current) input.current.value = ''; }
  }
  /** Export the electron reference-field timeline as CSV. */
  function csv() {
    const rows = ['tick,time_s,electron_x_R,beta,probe_valid,Ex_E0,Ey_E0,Ez_E0,Bmotion_x_B0,Bmotion_y_B0,Bmotion_z_B0,Bspin_x_B0,Bspin_y_B0,Bspin_z_B0'];
    for (let tick = 0; tick <= ELECTRON_END; tick += 12) { const st = { ...s, tick }, f = referenceFields(st, probePosition(p)); rows.push([tick, tick * ELECTRON_DT * TAU, electronX(st), velocity(p), f.valid, ...(f.valid ? [...f.electric, ...f.motion, ...f.intrinsic] : Array(9).fill(''))].join(',')); }
    downloadFile('zeropoint-electron-reference-sequence.csv', rows.join('\n'), 'text/csv'); setNotice('Exported the full analytic reference sequence, including future samples and the separate intrinsic-dipole reference.');
  }
  /** Select the displayed sample nearest to the configured probe. */
  function inspectProbe() { const shell = view.shells && p.mode === 'spin'; let best = shell ? LATTICE_SAMPLES : 0, distance = Infinity; for (let i = best; i < (shell ? LATTICE_SAMPLES + view.spinDisplay.count * SAMPLES_PER_SHELL : LATTICE_SAMPLES); i++) { const c = shellCentre(i, p.axis), r = Math.hypot(c[0] - p.probeX, c[1] - p.probeY, c[2] - p.probeZ); if (r < distance) { best = i; distance = r; } } setSelected(best); }
  const traces = Array.from({ length: 161 }, (_, i) => { const f = referenceFields({ ...s, tick: Math.round(s.tick * i / 160) }, probePosition(p)); return f.valid ? [f.electric[1], f.motion[2], p.mode === 'electric' ? 0 : f.intrinsic[2]] : null; });
  const max = Math.max(.01, ...traces.flatMap(v => v?.map(Math.abs) ?? []));
  const layers: [ElectronLayer, string][] = [['dipoles', 'Zepton pairs'], ['shells', 'Zepton shell sampling (spin view)'], ['faraday', 'Faraday lines from polarization'], ['electric', 'Radial electric reference'], ['rotation', 'Local rotation sense'], ['magnetic', 'Motion-induced magnetic field'], ['intrinsic', 'Intrinsic spin magnetic reference'], ['radius', 'Half-Compton radius guide'], ['cutaway', 'Central slab cutaway'], ['reducedMotion', 'Reduced flashing & camera motion']];

  return <div className={`light-app electron-app ${p.mode === 'spin' ? 'electron-spin-view' : ''}`} style={{ display: active ? undefined : 'none' }}>
    <header className="topbar"><div className="identity"><BrandMark/><span>ZeroPoint<span className="brand-period">.</span></span><span className="brand-divider"/><span className="lab-label">FIELD LABORATORY</span></div><div className="experiment-header-actions"><RepositoryLink/><button className="light-back" onClick={onBack}><ArrowLeft size={15}/><span className="back-label">Medium laboratory</span></button></div></header>
    <main className="light-workbench"><div className="light-heading"><div><div className="light-eyebrow">03 / THE ELECTRON & ITS FIELD</div><h1>Electron in the zero-point field</h1><p>Electric alignment. Local spin. Magnetism in motion.</p></div><a className="light-badge" href="./docs/electron-model.md" target="_blank" rel="noreferrer"><Info size={14}/>Fleming model illustration</a></div>
      <nav className="electron-modes" aria-label="Electron experiment stages">{modes.map(m => <button key={m.id} aria-pressed={p.mode === m.id} disabled={!ready} onClick={() => changeMode(m.id)}><small>{m.subtitle}</small><strong>{m.title}</strong></button>)}</nav>
      <div className="electron-explanation"><Info size={16}/><p>{mode.description}</p></div>
      <div className="light-toolbar"><div className="light-transport"><button className="play-button" disabled={!ready || finished || !!graphicsError} onClick={() => send({ type: 'run', value: !s.running })}>{s.running ? <Pause size={15}/> : <Play size={15}/>} {s.running ? 'Pause electron' : 'Run electron'}</button><button className="tool-button" disabled={!ready || finished} onClick={() => send({ type: 'step' })}><SkipForward size={15}/>Step</button><button className="light-next" disabled={!ready || finished} onClick={() => send({ type: 'advance' })}>Advance 1 τ</button><button className="tool-button" disabled={!ready} onClick={() => send({ type: 'reset' })}><RotateCcw size={14}/>Reset</button><select aria-label="Electron playback speed" value={s.speed} disabled={!ready} onChange={e => send({ type: 'speed', value: +e.target.value })}>{[.25, .5, 1, 2, 4].map(v => <option key={v} value={v}>{v}×</option>)}</select></div><div className="light-file-actions"><button disabled={!ready} onClick={() => input.current?.click()}>Load electron</button><button disabled={!ready} onClick={save}><Save size={14}/>Save electron</button><input ref={input} className="visually-hidden" type="file" accept=".json,application/json" aria-label="Import electron experiment" onChange={e => load(e.target.files?.[0])}/></div></div>
      {error && <div className="error-banner" role="alert">{error}<button onClick={() => { restart(); setDraft({ ...DEFAULT_ELECTRON }); }}>Restart electron worker</button></div>}
      <div className="light-layout"><div className="light-stage-column">
        <div className={p.mode === 'spin' && view.shells && view.spinDisplay.section ? 'electron-linked-views' : undefined}>
        <section className="light-viewport-shell" aria-label="Electron field visualization"><div className="light-viewport electron-viewport" ref={host}/><div className="light-view-top"><span><i className={`dot ${s.running ? '' : 'paused'}`}/>{s.running ? 'FIELD RESPONSE' : 'PAUSED'}</span><div>{(['front', 'orbit', 'probe'] as const).map(c => <button key={c} aria-pressed={camera === c} onClick={() => setCamera(c)}>{c === 'probe' ? <Focus size={13}/> : <Box size={13}/>} {c === 'front' ? 'Front' : c === 'orbit' ? 'Orbit' : 'Local close-up'}</button>)}</div></div><div className="light-stage-note"><span className="light-eyebrow">{p.mode === 'electric' ? `ALIGNMENT ${(alignmentProgress(s) * 100).toFixed(0)}%` : p.mode === 'spin' ? '01 / THREE-DIMENSIONAL SHELLS' : `${velocity(p).toFixed(2)} c ALONG X`}</span><strong>{p.mode === 'electric' ? (s.tick === 0 ? 'Unpolarized ZPF · electron not yet introduced' : electronPresence(s) < 1 ? 'Introducing the negative electron' : '+ ends align toward the electron') : p.mode === 'spin' ? 'Local turns around a stationary core' : 'The electron moves; the medium responds'}</strong><small>{p.mode === 'spin' ? 'Curled arrows turn at each pair · shaded plane links to 2D' : 'Faraday lines follow dipoles · field arrows are references'}</small></div><button className="light-png icon-button" aria-label="Export electron image" disabled={!ready || !!graphicsError} onClick={() => renderer.current?.exportPNG()}><Download size={16}/></button><div className="light-view-legend"><span><i className="charge positive"/>+ Positron</span><span><i className="charge negative"/>− Electron</span><span className="light-e">— Polarization / E</span><span className="light-b">— B motion</span><span className="electron-spin-colour">— B spin</span></div><div className="light-scale">R = λC/2 ≈ 1.213 pm · radius guide, not a solid shell</div>{graphicsError && <div className="graphics-error" role="alert"><h3>Electron viewport needs attention</h3><p>{graphicsError}</p><button onClick={() => { setGraphicsError(''); setRevision(v => v + 1); }}>Recover electron viewport</button></div>}</section>
        {p.mode === 'spin' && view.shells && view.spinDisplay.section && <SpinSection state={s} view={view} selected={selected} onPick={setSelected}/>}
        </div>
        <div className="electron-scene-options"><label><input type="checkbox" checked={view.inspect} onChange={e => { setView(v => ({ ...v, inspect: e.target.checked })); if (e.target.checked && selected === null) inspectProbe(); }}/>Zepton selector</label><span>{view.inspect ? 'Click a pair to inspect its fixed centre' : 'Selection off · drag to orbit the volume'}</span></div>
        {p.mode === 'spin' && <section className="light-card electron-shell-card" aria-label="Spin shell controls">
          <div className="light-card-heading"><h2>Explore the zepton shells</h2><button onClick={() => { setView(v => ({ ...v, shells: true })); setCamera('shell'); renderer.current?.cameraPreset('shell'); }}>Shell close-up</button></div>
          <div className="electron-spin-controls">
            <label>Visible shells<select aria-label="Visible spin shells" value={view.spinDisplay.count} onChange={e => setView(v => ({ ...v, spinDisplay: { ...v.spinDisplay, count: +e.target.value } }))}>{[1, 2, 3, 4].map(n => <option key={n} value={n}>{n === 1 ? '1 · Fig. 2 ring' : `${n} concentric shells`}</option>)}</select></label>
            <label>Adjacent shell preference<select aria-label="Adjacent shell preference" value={view.spinDisplay.alternating ? 'alternating' : 'shared'} onChange={e => setView(v => ({ ...v, spinDisplay: { ...v.spinDisplay, alternating: e.target.value === 'alternating' } }))}><option value="alternating">Alternating local turns</option><option value="shared">Shared local preference</option></select></label>
            <label>Turn magnification<select aria-label="Spin turn magnification" value={view.spinDisplay.gain} onChange={e => setView(v => ({ ...v, spinDisplay: { ...v.spinDisplay, gain: +e.target.value } }))}>{[1, 2, 4].map(n => <option key={n} value={n}>{n}× illustrative turn</option>)}</select></label>
          </div>
          <div className="electron-shell-actions">
            <label><input type="checkbox" checked={!view.cutaway} onChange={e => setView(v => ({ ...v, cutaway: !e.target.checked }))}/>Full 3D shells</label>
            <label><input type="checkbox" checked={view.spinDisplay.section} onChange={e => setView(v => ({ ...v, spinDisplay: { ...v.spinDisplay, section: e.target.checked } }))}/>Linked 2D section</label>
            <label><input type="checkbox" checked={view.rotation} onChange={e => setView(v => ({ ...v, rotation: e.target.checked }))}/>Local turn arrows</label>
            <label><input type="checkbox" checked={view.spinDisplay.guides} onChange={e => setView(v => ({ ...v, spinDisplay: { ...v.spinDisplay, guides: e.target.checked } }))}/>Shell guides</label>
          </div>
          {!view.shells && <p className="light-small">Shell sampling is hidden. Choose Shell close-up to restore the linked views.</p>}
          <div className="electron-rate-profile" aria-label="Illustrative shell rotation profile">{SHELL_RADII.slice(0, view.spinDisplay.count).map((r, i) => {
            const pair = displayedDipole(s, LATTICE_SAMPLES + i * SAMPLES_PER_SHELL + 34, view.spinDisplay);
            return <button key={r} aria-label={`Inspect spin band at ${r} R`} onClick={() => { setSelected(pair.index); setView(v => ({ ...v, shells: true, inspect: true })); }} style={{ borderColor: SHELL_COLOURS[i] }}>
              <span style={{ color: SHELL_COLOURS[i] }}>{shellSense(i, p.spin, view.spinDisplay.alternating) > 0 ? '↺' : '↻'} Shell {i + 1} · {r.toFixed(1)} R</span>
              <i style={{ width: `${100 * spinRateAtRadius(r) / spinRateAtRadius(.6)}%`, background: SHELL_COLOURS[i] }}/>
              <strong>{(pair.spinRate * 180 / Math.PI).toFixed(2)}°/τ</strong>
            </button>;
          })}</div>
          <p className="light-small">Turn directions are viewed from +{p.axis.toUpperCase()} toward the core. Reverse the spin projection in Electron & probe controls to reverse every shell. Playback, step and timeline control both views together.</p>
          <p className="light-small"><strong>{view.spinDisplay.alternating ? 'Alternating complete zepton shells is an illustrative extension.' : 'Shared preference illustrates the local coordination in §3.'}</strong> Fleming’s §4 counter-rotating charge shells are the inner + and outer − ends of a dipole, rather than a stated rule for successive whole zepton shells. The shell spacing, magnified turns and capped 1/r² rate are display assumptions.</p>
          <a className="light-small" href="./docs/electron-source-notes.md#figure-2-linked-shell-views" target="_blank" rel="noreferrer">Fig. 2 interpretation & visualization choices ↗</a>
          <div className="electron-replay-actions"><button disabled={!ready} onClick={() => { setView(v => ({ ...v, shells: true, inspect: true, spinDisplay: { ...v.spinDisplay, alternating: false, section: true } })); setSelected(LATTICE_SAMPLES + 34); setCamera('shell'); setNotice('Shared local preference selected, following the video’s coordination explanation at 4:44.'); }}>Explore the video’s shared rotation</button></div>
          <ChargeMotion state={s} index={view.inspect && selected !== null && selected >= LATTICE_SAMPLES && selected < LATTICE_SAMPLES + view.spinDisplay.count * SAMPLES_PER_SHELL ? selected : LATTICE_SAMPLES + 34} display={view.spinDisplay}/>
        </section>}
        <section className="light-metrics" aria-label="Electron diagnostics"><div><span>ELECTRON POSITION</span><strong data-testid="electron-position">{electronX(s).toFixed(3)}<small>R</small></strong><em>{velocity(p).toFixed(2)} c · bare core does not spin</em></div><div><span>MODEL TIME</span><strong>{time.toFixed(2)}<small>τ</small></strong><em data-testid="electron-tick">Tick {s.tick} · {(time * TAU).toExponential(2)} s</em></div><div><span>ENCLOSED CHARGE</span><strong>{flux.toFixed(4)}<small>e</small></strong><em>Gauss sphere · final-field reference</em></div><div><span>SPIN PROJECTION</span><strong>{p.spin > 0 ? '+½' : '−½'}<small>ℏ</small></strong><em>Reference choice · not derived here</em></div></section>
        <section className="light-card"><div className="light-card-heading"><h2>Replay the field response</h2><span>{p.mode === 'moving' ? 'Uniform motion · no acceleration event' : 'Core at rest throughout'}</span></div><label className="light-scrubber">Timeline<output>{time.toFixed(2)} / 48 τ</output><input aria-label="Electron timeline" type="range" min="0" max={ELECTRON_END} step="1" value={s.tick} disabled={!ready} onChange={e => send({ type: 'seek', tick: +e.target.value })}/></label><div className="electron-replay-actions">{p.mode === 'electric' && <button disabled={!ready} onClick={() => send({ type: 'seek', tick: 360 })}>Show fully aligned field</button>}{p.mode === 'moving' && <button disabled={!ready} onClick={() => send({ type: 'seek', tick: 2880 })}>Electron at path centre</button>}<button disabled={!ready} onClick={() => { const st = latest.current; if (st) setCheckpoints(old => [...old, { model: st.model, tick: st.tick, parameters: { ...st.parameters } }].slice(-4)); }}>Capture electron checkpoint</button>{checkpoints.map((c, i) => <button key={i} onClick={() => { send({ type: 'restore', state: c }); setDraft(c.parameters); }}>Restore electron tick {c.tick}</button>)}</div><p className="light-small">{p.mode === 'electric' ? 'The electron appears during the first 0.35 τ; nearby pairs then align before distant ones. The 3 τ introduction is an illustrative transition, not a calculated propagation time. Probe numbers are final-field analytic references.' : p.mode === 'spin' ? 'Each replacement pair starts partly aligned, turns toward the electron, and collapses. Both views show the same equatorial sites and generations. Outer pairs turn more slowly under the chosen display law; no centre orbits the electron.' : 'The path marks the prescribed electron trajectory. It is not a permanent magnetic wake; the reference field changes as the electron passes.'}</p></section>
        <section className="light-card"><div className="light-card-heading"><h2>Fixed probe · field history</h2><span>Lab coordinates ({vector(probePosition(p))}) R</span></div><div className="electron-chart"><svg viewBox="0 0 600 130" preserveAspectRatio="none" role="img" aria-label="Electric Y, motion magnetic Z, and intrinsic magnetic Z reference components at the fixed probe"><path d="M0 65H600" stroke="#3b515e" strokeDasharray="4 5"/>{['#93dec0', '#a894ef', '#efa5c1'].map((colour, j) => <path key={j} d={traces.map((v, i) => v ? `${i === 0 || !traces[i - 1] ? 'M' : 'L'}${i / 160 * 600},${65 - v[j] / max * 52}` : '').join(' ')} stroke={colour} fill="none" strokeWidth="1.7" vectorEffect="non-scaling-stroke"/>)}</svg><div><span>0 τ</span><span>Eᵧ/E₀ · Bmotion,z/B₀ · Bspin,z/B₀</span><span>{time.toFixed(2)} τ</span></div></div><p className="light-small">Reference components use normalized units; gaps mark the excluded central region. Intrinsic spin magnetism is a separate dipole reference, not part of B = v × E / c².</p></section>
        <ElectronProperties/>
        <section className="light-card electron-reading"><div className="light-card-heading"><h2>What the source papers contribute</h2></div><div><article><strong>Polarization → electric field</strong><p>A bare negative polarizer aligns positive dipole ends inward. Fleming relates the surrounding polarization flux to unit charge.</p><a href="./docs/papers/Electron%20Properties%20Explained%20as%20Quantum%20Field%20Effects.pdf#page=2" target="_blank" rel="noreferrer">Electron properties · §2 ↗</a></article><article><strong>Preferred local rotation → spin</strong><p>Neighboring partially aligned dipoles favor a common rotation sense. Their centres and the bare core need not move.</p><a href="./docs/papers/Electron%20Properties%20Explained%20as%20Quantum%20Field%20Effects.pdf#page=3" target="_blank" rel="noreferrer">Electron properties · §§3–6 ↗</a></article><article><strong>Polarization rate → radius</strong><p>R = λC/2 gives an effective rate c/(2πR) ≈ 3.933 × 10¹⁹ turns/s in Fleming’s radius argument.</p><a href="./docs/papers/Electron%20and%20proton%20radii%20are%20due%20to%20quantum%20polarization%20rate%20and%20the%20speed%20of%20light.pdf#page=3" target="_blank" rel="noreferrer">Radii paper · §4 ↗</a></article></div></section>
        <div className="light-footnote"><a href="./docs/electron-source-notes.md" target="_blank" rel="noreferrer">Read extracted source details & model decisions ↗</a><button disabled={!ready} onClick={csv}><Download size={13}/>Export electron CSV</button></div>
      </div><aside className="light-controls" aria-label="Electron controls">
        <section className="light-card"><div className="light-card-heading"><h2>Electron & probe controls</h2><span>Apply changes to a new paused run</span></div><form onSubmit={e => { e.preventDefault(); send({ type: 'configure', parameters: draft }); setNotice('Electron parameters applied. Paused at tick 0.'); }}>
          <label className="light-range">Signed velocity<output>{draft.beta.toFixed(2)} c</output><input aria-label="Electron velocity" type="range" min="-.2" max=".2" step=".01" value={draft.beta} disabled={p.mode !== 'moving'} onChange={e => setDraft(v => ({ ...v, beta: +e.target.value }))}/></label><small className="light-form-note">Velocity applies in Moving electron.</small>
          <label className="light-direction">Spin projection<select aria-label="Electron spin projection" value={draft.spin} onChange={e => setDraft(v => ({ ...v, spin: +e.target.value as 1 | -1 }))}><option value="1">+½ ℏ</option><option value="-1">−½ ℏ</option></select></label><label className="light-direction">Preferred axis<select aria-label="Electron spin axis" value={draft.axis} onChange={e => setDraft(v => ({ ...v, axis: e.target.value as 'x' | 'y' | 'z' }))}>{['x', 'y', 'z'].map(axis => <option key={axis} value={axis}>{axis.toUpperCase()}</option>)}</select></label>
          {([['probeX', 'Probe X', -5, 5], ['probeY', 'Probe Y', -4, 4], ['probeZ', 'Probe Z', -3, 3]] as const).map(([key, label, min, max]) => <label className="light-range" key={key}>{label}<output>{draft[key].toFixed(1)} R</output><input aria-label={label} type="range" min={min} max={max} step=".1" value={draft[key]} onChange={e => setDraft(v => ({ ...v, [key]: +e.target.value }))}/></label>)}<button className="light-apply" disabled={!ready} type="submit">Apply electron parameters</button>
        </form></section>
        <section className="light-card"><div className="light-card-heading"><h2>Probe reference readout</h2><span>Components (X, Y, Z)</span></div>{field.valid ? <dl className="light-readouts"><div><dt>Electric / E₀</dt><dd data-testid="electron-E">{vector(field.electric)}</dd></div><div><dt>Motion B / B₀</dt><dd data-testid="electron-B-motion">{vector(field.motion)}</dd></div><div><dt>Intrinsic B / B₀</dt><dd>{p.mode === 'electric' ? 'Hidden in electric-only view' : vector(field.intrinsic)}</dd></div><div><dt>Distance to electron</dt><dd>{field.radius.toFixed(3)} R</dd></div></dl> : <p className="electron-excluded" role="status">Probe lies inside the 0.3 R numerical mask. Field values are excluded.</p>}<p className="light-small">E₀ = e/(4πε₀R²), B₀ = E₀/c. Motion field vanishes at zero velocity. Intrinsic magnetism can remain at rest.</p></section>
        <section className="light-card"><div className="light-card-heading"><h2>Inspect a zepton</h2><button disabled={!view.inspect} onClick={inspectProbe}>Nearest to probe</button></div>{picked && <><div className="electron-pair-signs"><span>+</span><i/><span>−</span></div><dl className="light-readouts"><div><dt>Sample / generation</dt><dd>{picked.index} / {picked.generation}</dd></div><div><dt>Fixed centre (R)</dt><dd data-testid="electron-pair-centre">{vector(picked.centre)}</dd></div><div><dt>Age / lifetime (τ)</dt><dd>{picked.age.toFixed(2)} / {picked.lifetime.toFixed(2)}</dd></div><div><dt>Full separation</dt><dd>{picked.separation.toFixed(3)} R</dd></div><div><dt>Local spin turn</dt><dd data-testid="electron-local-spin">{(picked.spinTurn * 180 / Math.PI).toFixed(2)}° / lifecycle</dd></div><div><dt>Spin rate (illustrative)</dt><dd data-testid="electron-spin-rate">{(picked.spinRate * 180 / Math.PI).toFixed(2)}° / τ</dd></div><div><dt>Motion turn</dt><dd>{(picked.motionTurn * 180 / Math.PI).toFixed(2)}° / lifecycle</dd></div></dl>{!picked.field.valid && <p className="light-small">This sample is currently inside the electron’s numerical mask.</p>}<button className="light-focus" onClick={() => { setCamera('probe'); renderer.current?.cameraPreset('probe'); }}><Focus size={14}/>Inspect this fixed centre</button></>}<p className="light-small">Enable the zepton selector, then click a pair or choose Nearest to probe. Selection pins a fixed sampling location across successive pair generations.</p></section>
        <section className="light-card"><div className="light-card-heading"><h2>Scene layers</h2></div>{layers.map(([key, label]) => <label className="light-toggle" key={key}><span>{label}</span><input type="checkbox" checked={view[key]} onChange={e => setView(v => ({ ...v, [key]: e.target.checked }))}/></label>)}<p className="light-small">Faraday lines trace the neighboring dipoles’ mean alignment, with arrows toward positive ends. Line spacing is illustrative. Magnetic guides follow the motion-induced rotation direction.</p><a className="light-small" href="./docs/Polarization-Notes.md" target="_blank" rel="noreferrer">Polarization notes ↗</a></section>
        <section className="light-card"><div className="light-card-heading"><h2>Source scale & constants</h2><span>Reference inputs, not fitted outputs</span></div><dl className="light-readouts"><div><dt>R = λC/2</dt><dd>{(RADIUS * 1e12).toFixed(6)} pm</dd></div><div><dt>c/(2πR)</dt><dd>{(C / (2 * Math.PI * RADIUS)).toExponential(3)} Hz</dd></div><div><dt>α</dt><dd>1 / {(1 / ALPHA).toFixed(6)}</dd></div><div><dt>μ along preferred axis</dt><dd>{(-p.spin * G_FACTOR / 2).toFixed(6)} μB</dd></div></dl><p className="light-small">Fleming interprets α as total polarization. This experiment does not derive α, quantized spin, magnetic moment or mass from dipole interactions.</p></section>
      </aside></div><div className="light-status" role="status" aria-label="Electron experiment status">{notice || 'Start with Run electron to introduce the electron and watch the field resolve. Space pauses; Right arrow steps. Each experiment keeps its own paused state.'}</div>
    </main><footer className="statusbar"><span><i className="dot"/>{ELECTRON_MODEL} · {s.running ? 'Running' : 'Paused'} · τ = R/c</span><span>Fixed zepton centres · local worker · source-linked model</span></footer>
  </div>;
}
