// Generate src/ui/palette.ts, the TypeScript mirror of the colour tokens in src/ui/tokens.css, for colours that can't
// use CSS variables (Three.js materials, canvas drawing, SVG built in components). Scene constants (lighting and
// emissive glows) are rendering parameters rather than design tokens; they are named here so no colour literal lives
// anywhere else. Usage: node scripts/sync-palette.mjs  (tests/tokens-lint.test.ts checks palette.ts is in sync)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readTokens } from './tokens-preview.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const PALETTE_FILE = join(root, 'src', 'ui', 'palette.ts');

/** Scene constants: lighting and emissive glows per laboratory, kept at their current values. */
export const SCENE = {
  keyLight: '#ffffff',
  ambientMedium: '#b5d3e7', ambientLight: '#a9cfe0', ambientElectron: '#c4d6e6',
  posGlowMedium: '#ad431e', negGlowMedium: '#23638b',
  posGlowLight: '#8c391a', negGlowLight: '#205773',
  posGlowElectron: '#672e17', negGlowElectron: '#1c4c6c', coreGlowElectron: '#7e42ce',
};

/** Convert a token name (--data-pos-hi) to its palette key (dataPosHi). */
export const paletteKey = name => name.replace(/^--/, '').replace(/-(\w)/g, (_, c) => c.toUpperCase());

/** Render palette.ts from the tokens and scene constants. */
export function renderPalette(tokens) {
  const lines = tokens.map(t => `  ${paletteKey(t.name)}: '${t.hex}',`);
  return `// Generated by scripts/sync-palette.mjs from src/ui/tokens.css; do not edit by hand.
/** Colour tokens for code that cannot use CSS variables (Three.js, canvas, generated SVG). */
export const palette = {
${lines.join('\n')}
} as const;

/** Scene constants: lighting and emissive glows are rendering parameters, not design tokens. */
export const scene = {
${Object.entries(SCENE).map(([key, hex]) => `  ${key}: '${hex}',`).join('\n')}
} as const;
`;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const tokens = readTokens(readFileSync(join(root, 'src', 'ui', 'tokens.css'), 'utf8'));
  writeFileSync(PALETTE_FILE, renderPalette(tokens));
  console.log(`src/ui/palette.ts: ${tokens.length} tokens, ${Object.keys(SCENE).length} scene constants`);
}
