import React from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './app/App';
import { DevProfiler } from './app/DevProfiler';
import '@fontsource/dm-sans/latin-400.css';
import '@fontsource/dm-sans/latin-500.css';
import '@fontsource/dm-sans/latin-600.css';
import '@fontsource/dm-sans/latin-700.css';
import '@fontsource/ibm-plex-mono/latin-400.css';
import '@fontsource/ibm-plex-mono/latin-500.css';
import './ui/tokens.css';
import './app/styles.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><DevProfiler id="app"><App /></DevProfiler></React.StrictMode>);
